/* SAMPLE TEST DATA FOR SmartOrchestra-1.0.1.Final */
/* Run this file in an empty smartorchestra databased with DDL structure newely created! */
/* Creates sections */
INSERT INTO public.sections(SectionName, SectionType) VALUES
    ('I. Housle', 'STRINGS'),
    ('II. Housle', 'STRINGS'),
    ('Viola', 'STRINGS'),
    ('Violoncello', 'STRINGS'),
    ('Příčná flétna', 'WINDS'),
    ('Klarinet', 'WINDS'),
    ('Trubka', 'WINDS'),
    ('Pozoun', 'WINDS'),
    ('Sbor', 'OTHER'),
    ('Klavír', 'OTHER');

/* Creating Users and Players */
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Adriana','Kocourková', (SELECT to_date('09.04.2000', 'dd.mm.yyyy')),'adriana.kocourkova@smorch.net','+420696581268','30','Harrachov','51301','Sekorova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Stela','Burešová', (SELECT to_date('03.02.1999', 'dd.mm.yyyy')),'stela.buresova@smorch.net','+420720592950','228','Studenec','51204','U Čekárny') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Martina','Havlíková', (SELECT to_date('01.10.1985', 'dd.mm.yyyy')),'martina.havlikova@smorch.net','+420611432716','478','Bozkov','51263','Obchodní náměstí') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Jana','Vlková', (SELECT to_date('08.08.1989', 'dd.mm.yyyy')),'jana.vlkova@smorch.net','+420699868512','348','Víchová nad Jizerou','51101','Nad Doly') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Klára','Šebková', (SELECT to_date('03.10.1984', 'dd.mm.yyyy')),'klara.sebkova@smorch.net','+420790418500','123','Horní Branná','51101','Staromodřanská') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Klára','Krejčová', (SELECT to_date('15.06.1998', 'dd.mm.yyyy')),'klara.krejcova@smorch.net','+420705824104','335','Mříčná','51301','Na Havránce') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Bára','Kuncová', (SELECT to_date('12.05.1983', 'dd.mm.yyyy')),'bara.kuncova@smorch.net','+420631444123','328','Loučky','51401','Pertoldova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Magdalena','Lukešová', (SELECT to_date('26.12.2001', 'dd.mm.yyyy')),'magdalena.lukesova@smorch.net','+420626174668','466','Semily','51401','Chuchelská') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Aneta','Ondráčková', (SELECT to_date('05.11.1987', 'dd.mm.yyyy')),'aneta.ondrackova@smorch.net','+420626105697','210','Harrachov','51263','Pod Belárií') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Ela','Davidová', (SELECT to_date('09.08.1998', 'dd.mm.yyyy')),'ela.davidova@smorch.net','+420631791932','177','Tatobity','51101','Ke Schodům') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Viola' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Sára','Válková', (SELECT to_date('07.08.1996', 'dd.mm.yyyy')),'sara.valkova@smorch.net','+420700822529','326','Troskovice','51101','Semická') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Viola' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Veronika','Kocourková', (SELECT to_date('16.07.1986', 'dd.mm.yyyy')),'veronika.kocourkova@smorch.net','+420727480356','113','Modřišice','51233','Ploštilova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Barbora','Čermáková', (SELECT to_date('05.02.1986', 'dd.mm.yyyy')),'barbora.cermakova@smorch.net','+420727536264','340','Vítkovice','51401','Ke Spofě') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Alice','Hlaváčková', (SELECT to_date('27.04.1987', 'dd.mm.yyyy')),'alice.hlavackova@smorch.net','+420672448422','188','Syřenov','51243','Hřebíkova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Příčná flétna' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Klaudie','Kalinová', (SELECT to_date('17.01.1995', 'dd.mm.yyyy')),'klaudie.kalinova@smorch.net','+420664165463','459','Horka u Staré Paky','51401','Soukalova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Příčná flétna' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Lenka','Turková', (SELECT to_date('03.04.1984', 'dd.mm.yyyy')),'lenka.turkova@smorch.net','+420703588168','60','Benešov u Semil','51101','Okružní') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Příčná flétna' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Terezie','Čechová', (SELECT to_date('12.11.1999', 'dd.mm.yyyy')),'terezie.cechova@smorch.net','+420674380908','83','Lomnice nad Popelkou','51301','Za Strojírnami') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klarinet' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Anna','Vaňková', (SELECT to_date('10.02.1996', 'dd.mm.yyyy')),'anna.vankova@smorch.net','+420633771245','254','Vítkovice','51253','Na Blanseku') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klarinet' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Ester','Vlachová', (SELECT to_date('14.03.1981', 'dd.mm.yyyy')),'ester.vlachova@smorch.net','+420623812535','292','Svojek','51242','Jordana Jovkova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klarinet' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Václav','Kovařík', (SELECT to_date('29.09.1989', 'dd.mm.yyyy')),'vaclav.kovařik@smorch.net','+420792205313','13','Žernov','51251','Barrandova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Kryštof','Filip', (SELECT to_date('04.12.1993', 'dd.mm.yyyy')),'krystof.filip@smorch.net','+420646552236','499','Vyskeř','51236','Sofijské náměstí') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Jaroslav','Moravec', (SELECT to_date('20.01.1990', 'dd.mm.yyyy')),'jaroslav.moravec@smorch.net','+420686904480','443','Chuchelna','51251','Rilská') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Milan','Pokorný', (SELECT to_date('22.02.1995', 'dd.mm.yyyy')),'milan.pokorny@smorch.net','+420703246295','2','Syřenov','51243','Baumanské náměstí') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'II. Housle' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Tobiáš','Sláma', (SELECT to_date('14.02.1990', 'dd.mm.yyyy')),'tobias.slama@smorch.net','+420735301652','294','Jestřabí v Krkonoších','51251','U Spořitelny') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Viola' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Vít','Sýkora', (SELECT to_date('14.07.1988', 'dd.mm.yyyy')),'vit.sykora@smorch.net','+420773901989','42','Vysoké nad Jizerou','51101','Na Havránce') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Viola' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Oliver','Richter', (SELECT to_date('24.11.1997', 'dd.mm.yyyy')),'oliver.richter@smorch.net','+420715730238','157','Čistá u Horek','51237','U Kovárny') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Adrian','Soukup', (SELECT to_date('07.04.1984', 'dd.mm.yyyy')),'adrian.soukup@smorch.net','+420775844680','431','Slaná','51101','Lhotecká') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Gabriel','Horký', (SELECT to_date('19.09.1997', 'dd.mm.yyyy')),'gabriel.horky@smorch.net','+420724431156','403','Přepeře','51251','Ploštilova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Benjamin','Svoboda', (SELECT to_date('29.11.1999', 'dd.mm.yyyy')),'benjamin.svoboda@smorch.net','+420634957576','98','Rakousy','51401','Pejevové') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Příčná flétna' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Štěpán','Horký', (SELECT to_date('20.03.1984', 'dd.mm.yyyy')),'stěpan.horky@smorch.net','+420753471788','78','Libštát','50601','Barrandova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Příčná flétna' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Albert','Černý', (SELECT to_date('24.02.1993', 'dd.mm.yyyy')),'albert.cerny@smorch.net','+420714623141','100','Libštát','51301','Amortova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klarinet' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Sebastián','Horváth', (SELECT to_date('20.06.2001', 'dd.mm.yyyy')),'sebastian.horvath@smorch.net','+420762864175','212','Roprachtice','51204','Skalnatá') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klarinet' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Jan','Kratochvíl', (SELECT to_date('14.03.1999', 'dd.mm.yyyy')),'jan.kratochvil@smorch.net','+420671338193','446','Chuchelna','51101','Platónova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Trubka' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Theodor','Hruška', (SELECT to_date('27.09.1985', 'dd.mm.yyyy')),'theodor.hruska@smorch.net','+420740101954','90','Semily','51301','Na Výšině') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Trubka' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Vít','Kučera', (SELECT to_date('27.01.1991', 'dd.mm.yyyy')),'vit.kucera@smorch.net','+420616315388','486','Roztoky u Semil','51204','Nečova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Trubka' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Jakub','Sikora', (SELECT to_date('14.09.1982', 'dd.mm.yyyy')),'jakub.sikora@smorch.net','+420742143606','403','Klokočí','51253','K Lahovičkám') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Pozoun' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Miroslav','Horáček', (SELECT to_date('13.12.1982', 'dd.mm.yyyy')),'miroslav.horacek@smorch.net','+420606270982','237','Roztoky u Semil','51301','Hrubínova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Pozoun' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Michael','Kolář', (SELECT to_date('31.12.1985', 'dd.mm.yyyy')),'michael.kolař@smorch.net','+420690831153','472','Jesenný','51401','Pod Sady') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Pozoun' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Alexander','Špaček', (SELECT to_date('23.08.1985', 'dd.mm.yyyy')),'alexander.spacek@smorch.net','+420739683855','437','Semily','51301','Na Cimbále') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Violoncello' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Šimon','Jedlička', (SELECT to_date('17.12.2000', 'dd.mm.yyyy')),'simon.jedlicka@smorch.net','+420672991823','232','Čistá u Horek','51401','Na Floře') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Viola' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Samuel','Hanuš', (SELECT to_date('07.01.1998', 'dd.mm.yyyy')),'samuel.hanus@smorch.net','+420671624983','141','Troskovice','51101','Mráčkova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'Klavír' LIMIT 1));
WITH rows AS ( INSERT INTO Users(Passwd, FirstName, FamilyName, BirthDate, Email, Phone, AddrHouseNumber, AddrTown, AddrZipCode, AddrStreet) VALUES('$2a$12$6GbZJxLX65LYW5f5zjSkx.moj3Q7f9xlDuqc1kjAWnc0HQvjqN4Du','Lukáš','Krátký', (SELECT to_date('27.04.1982', 'dd.mm.yyyy')),'lukas.kratky@smorch.net','+420760600626','432','Klokočí','51271','Benáčanova') RETURNING users.uid ) INSERT INTO player (uid, seid) VALUES ((SELECT uid FROM rows), ( SELECT sections.seid FROM sections WHERE sectionName LIKE 'I. Housle' LIMIT 1));



/* Creating Events */
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('08.05.2020 21:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('08.05.2020 22:00', 'DD.MM.YYYY HH24:MI')),'Kulturní dům','Rakovského','59','Jestřabí v Krkonoších','51401');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('28.03.2020 21:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('28.03.2020 22:00', 'DD.MM.YYYY HH24:MI')),'Hospoda U Dubu','Lešetínská','174','Přepeře','51251');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('17.07.2019 17:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('17.07.2019 18:00', 'DD.MM.YYYY HH24:MI')),'Kostel sv. Kateřiny','U Pily','347','Tatobity','51101');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('19.02.2020 20:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('19.02.2020 21:30', 'DD.MM.YYYY HH24:MI')),'Kostel sv. Kateřiny','Vokrajová','115','Turnov','51231');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('22.09.2019 18:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('22.09.2019 19:30', 'DD.MM.YYYY HH24:MI')),'ZUŠ Františka Kmocha','Lešetínská','498','Turnov','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('28.06.2019 18:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('28.06.2019 19:00', 'DD.MM.YYYY HH24:MI')),'ZUŠ Františka Kmocha','Odbočná','244','Tatobity','50601');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('25.09.2019 17:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('25.09.2019 18:30', 'DD.MM.YYYY HH24:MI')),'Obecní divadlo','Na Blanseku','486','Mříčná','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('09.07.2019 21:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('09.07.2019 22:30', 'DD.MM.YYYY HH24:MI')),'Hospoda U Dubu','Ke Srážku','270','Holenice','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('12.01.2020 21:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('12.01.2020 22:00', 'DD.MM.YYYY HH24:MI')),'Obecní divadlo','U Pily','222','Bukovina u Čisté','50601');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('05.10.2019 19:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('05.10.2019 20:30', 'DD.MM.YYYY HH24:MI')),'Kulturní dům','V Dolech','323','Benešov u Semil','51202');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('07.06.2019 18:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('07.06.2019 19:00', 'DD.MM.YYYY HH24:MI')),'Kostel Panny Marie Lurdské','Revoluce','233','Klokočí','51247');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('24.10.2019 21:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('24.10.2019 22:30', 'DD.MM.YYYY HH24:MI')),'Kostel Panny Marie Lurdské','Bojovská','455','Loučky','51101');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('27.09.2019 17:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('27.09.2019 18:00', 'DD.MM.YYYY HH24:MI')),'Obecní divadlo','Na Havránce','424','Rakousy','51206');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('03.02.2020 21:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('03.02.2020 22:00', 'DD.MM.YYYY HH24:MI')),'Hospoda U Dubu','Převoznická','90','Stružinec','51401');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('20.04.2020 18:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('20.04.2020 19:00', 'DD.MM.YYYY HH24:MI')),'Kostel sv. Kateřiny','Božetická','219','Vítkovice','51242');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Koncert', ( SELECT to_timestamp('02.10.2019 20:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('02.10.2019 21:00', 'DD.MM.YYYY HH24:MI')),'Hospoda U Dubu','Daškova','97','Lomnice nad Popelkou','51101');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('30.12.2019 20:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('30.12.2019 21:00', 'DD.MM.YYYY HH24:MI')),'Hospoda U Dubu','Pacholíkova','69','Horní Branná','51271');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('19.12.2019 17:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('19.12.2019 18:00', 'DD.MM.YYYY HH24:MI')),'Kulturní dům','K Orionce','399','Turnov','51401');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Koncert', ( SELECT to_timestamp('17.02.2020 16:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('17.02.2020 17:30', 'DD.MM.YYYY HH24:MI')),'Kostel sv. Kateřiny','Revoluce','134','Slaná','51261');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('06.03.2018 20:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('06.03.2018 21:00', 'DD.MM.YYYY HH24:MI')),'Kulturní dům','Sofijské náměstí','254','Hrubá Skála','51204');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('21.05.2018 17:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('21.05.2018 18:00', 'DD.MM.YYYY HH24:MI')),'Podkrkonošská konzervatoř','Dolnocholupická','25','Čistá u Horek','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('13.01.2018 18:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('13.01.2018 19:00', 'DD.MM.YYYY HH24:MI')),'ZUŠ Františka Kmocha','V Potočkách','118','Turnov','51101');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('17.02.2018 16:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('17.02.2018 17:30', 'DD.MM.YYYY HH24:MI')),'ZUŠ Františka Kmocha','Vltavanů','62','Jesenný','51265');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Koncert', ( SELECT to_timestamp('18.03.2018 17:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('18.03.2018 18:30', 'DD.MM.YYYY HH24:MI')),'Kulturní dům','U Tyršovky','392','Paseky nad Jizerou','51204');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Koncert', ( SELECT to_timestamp('02.10.2018 21:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('02.10.2018 22:30', 'DD.MM.YYYY HH24:MI')),'Podkrkonošská konzervatoř','U Cihelny','397','Benecko','51201');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('26.10.2018 19:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('26.10.2018 20:00', 'DD.MM.YYYY HH24:MI')),'Podkrkonošská konzervatoř','Za Strojírnami','487','Stružinec','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Generálka', ( SELECT to_timestamp('01.07.2018 20:30', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('01.07.2018 21:30', 'DD.MM.YYYY HH24:MI')),'Obecní divadlo','Sekorova','248','Olešnice','51301');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Zkouška', ( SELECT to_timestamp('30.09.2018 17:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('30.09.2018 18:00', 'DD.MM.YYYY HH24:MI')),'Kostel sv. Kateřiny','Rakovského','72','Jilemnice','51243');
INSERT INTO Events (EventName, Begins, Ends, AddrInstitution, AddrStreet, AddrHouseNumber, AddrTown, AddrZipCode) VALUES ('Mimořádná zkouška', ( SELECT to_timestamp('30.07.2018 18:00', 'DD.MM.YYYY HH24:MI')), ( SELECT to_timestamp('30.07.2018 19:00', 'DD.MM.YYYY HH24:MI')),'Podkrkonošská konzervatoř','Barunčina','213','Loučky','51101');

/* Sample participations */
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',17,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',31,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',18,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',20,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',33,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',34,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',39,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',6,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',21,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',43,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',3,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',5,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',7,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',22,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',25,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',41,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',13,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',14,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',40,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',31,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',18,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',20,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',32,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',33,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',42,21);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',10,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',3,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',7,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',9,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',24,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',41,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',14,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',40,24);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',6,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',5,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',9,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',22,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',24,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',11,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',12,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',26,26);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',6,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',21,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',43,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',7,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',22,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',41,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',28,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',15,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',17,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',20,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',42,25);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',34,28);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',4,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',43,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',7,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',9,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',13,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',40,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',33,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',35,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',36,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',37,29);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',4,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',6,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',10,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',21,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',30,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',19,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',38,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',42,22);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',6,23);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',9,23);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',11,23);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',14,23);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',27,23);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',17,20);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',30,20);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',2,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',6,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',21,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',41,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',16,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',37,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',38,11);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',2,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',21,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',23,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',9,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',24,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',11,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',25,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',26,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',13,6);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',16,8);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',20,8);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',36,8);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',6,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',8,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',21,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',43,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',9,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',11,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',12,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',40,3);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',2,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',8,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',10,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',3,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',7,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',41,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',29,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',19,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',32,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',36,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',42,5);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Pracovní neschopnost',43,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',22,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',24,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',27,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Jsem líný.',29,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',15,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',18,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',38,9);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',8,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',21,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',5,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',11,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',12,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',27,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',40,1);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',20,15);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',2,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',6,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',43,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',13,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',16,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',17,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',19,2);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',41,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',7,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rozbitý nástroj',9,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Dovolená',27,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nechce se mi.',28,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Nemoc',29,4);
INSERT INTO participants (active, message, uid, seid) VALUES (FALSE, 'Rodinné důvody',37,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 23,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 3,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 7,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 12,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 14,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 29,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 18,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 35,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 42,11);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 4,6);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 8,6);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 22,6);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 40,6);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 15,8);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 32,8);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 3,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 5,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 22,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 24,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 25,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 26,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 27,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 28,3);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 6,5);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 13,5);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 15,5);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 33,5);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 38,5);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 2,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 23,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 26,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 28,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 17,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 30,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 20,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 32,9);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 10,1);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 26,1);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 29,1);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 16,15);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 18,15);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 34,15);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 36,15);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 10,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 21,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 22,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 12,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 14,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 27,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 28,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 29,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 31,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 33,2);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 8,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 21,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 25,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 17,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 36,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 13,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 19,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 20,4);
INSERT INTO participants (active, message, uid, seid) VALUES (NULL, NULL, 38,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,21);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 42,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,24);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,26);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,25);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,28);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 42,29);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,22);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,23);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 42,20);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,11);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,6);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,8);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 29,3);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 27,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,5);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 21,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,9);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 13,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 28,1);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 17,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 19,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,15);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 8,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 7,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 9,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 25,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 41,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 20,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 36,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 37,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 38,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,2);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 2,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 4,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 6,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 10,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 23,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 43,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 11,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 12,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 26,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 15,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 16,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 30,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 31,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 34,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 35,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 3,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 5,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 22,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 24,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 14,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 40,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 18,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 32,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 33,4);
INSERT INTO participants (active, message, uid, seid) VALUES (TRUE, NULL, 39,4);
