/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.dbs.smartorchestra.gui;

import cz.cvut.fel.dbs.smartorchestra.MainControl;
import cz.cvut.fel.dbs.smartorchestra.SmartOrchestra;
import cz.cvut.fel.dbs.smartorchestra.UIControlled;
import cz.cvut.fel.dbs.smartorchestra.model.entities.Users;
import java.awt.Dimension;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Matěj Bartoň
 */
public class Main extends javax.swing.JFrame implements UIControlled<MainControl>{
    public static final String[] USERS_COLUMN_NAMES = new String [] {
                "Příjmení", "Jméno", "Datum narození:", "Bydliště:", "Telefon:", "Email:", "Sekce:"
            };
    private MainControl controller;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setUIController(SmartOrchestra.getInstance().getController(this));
        controller.loadEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        content = new javax.swing.JTabbedPane();
        events = new cz.cvut.fel.dbs.smartorchestra.gui.ShowEvents();
        jPanel1 = new javax.swing.JPanel();
        userToolbar = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        labelSearchUser = new javax.swing.JLabel();
        fieldSearchUser = new javax.swing.JTextField();
        labelFilterSection = new javax.swing.JLabel();
        fieldFilterSection = new javax.swing.JComboBox<>();
        btnSearchUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        userContent = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileAddEvent = new javax.swing.JMenuItem();
        fileAddUser = new javax.swing.JMenuItem();
        fileSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileViewProfile = new javax.swing.JMenuItem();
        fileSeparator2 = new javax.swing.JPopupMenu.Separator();
        fileQuit = new javax.swing.JMenuItem();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(18, 40));
        jToolBar1.setMinimumSize(new java.awt.Dimension(18, 40));

        jButton1.setText("Přidat událost");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Přidat uživatele");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Můj profil");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("SmartOrchestra"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 400));

        content.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                contentStateChanged(evt);
            }
        });
        content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentMouseClicked(evt);
            }
        });
        content.addTab("Přehled událostí", events);

        jPanel1.setLayout(new java.awt.BorderLayout());

        userToolbar.setFloatable(false);
        userToolbar.setRollover(true);
        userToolbar.setMaximumSize(new java.awt.Dimension(18, 40));
        userToolbar.setMinimumSize(new java.awt.Dimension(18, 40));
        userToolbar.setPreferredSize(new java.awt.Dimension(40, 50));

        labelSearchUser.setText("Vyhledat uživatele:");

        labelFilterSection.setText("Zobraz sekci:");

        fieldFilterSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "všechny", "1. Housle", "2. Housle", "Viola", "Violoncello", "Kontrabas" }));
        fieldFilterSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFilterSectionActionPerformed(evt);
            }
        });

        btnSearchUser.setText("Hledej");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });

        btnAddUser.setText("Přidat uživatele");
        btnAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddUserMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelSearchUser)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fieldSearchUser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 163, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSearchUser)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(labelFilterSection)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(fieldFilterSection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnAddUser)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(btnSearchUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(fieldSearchUser)
                        .add(labelSearchUser, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(labelFilterSection, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(fieldFilterSection, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(btnAddUser)))
                .add(12, 12, 12))
        );

        userToolbar.add(jPanel2);

        jPanel1.add(userToolbar, java.awt.BorderLayout.PAGE_START);

        userContent.setMinimumSize(new Dimension(getWidth(), getHeight() - userToolbar.getHeight() - mainMenu.getHeight()));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Josefína", "Abuzaradová", "31.12.2019", "Klášterec nad Ohří", "+420 777 777 777", "josefina.abuzaradova@ensembleacademia.cz", "příčná flétna"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Jméno", "Příjmení", "Datum narození:", "Bydliště:", "Telefon:", "Email:", "Sekce:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        userTable.setAutoscrolls(false);
        userTable.setMaximumSize(new java.awt.Dimension(1185, 16));
        userTable.setMinimumSize(new java.awt.Dimension(1185, 16));
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userTable.setShowHorizontalLines(false);
        userTable.setShowVerticalLines(false);
        userTable.getTableHeader().setResizingAllowed(false);
        userTable.getTableHeader().setReorderingAllowed(false);
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        userContent.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            userTable.getColumnModel().getColumn(3).setResizable(false);
            userTable.getColumnModel().getColumn(3).setPreferredWidth(175);
            userTable.getColumnModel().getColumn(4).setResizable(false);
            userTable.getColumnModel().getColumn(4).setPreferredWidth(200);
            userTable.getColumnModel().getColumn(5).setResizable(false);
            userTable.getColumnModel().getColumn(5).setPreferredWidth(250);
            userTable.getColumnModel().getColumn(6).setResizable(false);
            userTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jPanel1.add(userContent, java.awt.BorderLayout.CENTER);

        content.addTab("Přehled uživatelů", jPanel1);

        getContentPane().add(content, java.awt.BorderLayout.PAGE_START);

        fileMenu.setText("Soubor");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        fileAddEvent.setText("Přidat událost");
        fileAddEvent.setEnabled(false);
        fileMenu.add(fileAddEvent);

        fileAddUser.setText("Přidat uživatele");
        fileAddUser.setEnabled(false);
        fileAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileAddUserActionPerformed(evt);
            }
        });
        fileMenu.add(fileAddUser);
        fileMenu.add(fileSeparator1);

        fileViewProfile.setText("Zobrazit profil");
        fileViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileViewProfileMouseClicked(evt);
            }
        });
        fileViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileViewProfileActionPerformed(evt);
            }
        });
        fileMenu.add(fileViewProfile);
        fileMenu.add(fileSeparator2);

        fileQuit.setText("Ukončit aplikaci");
        fileQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileQuitActionPerformed(evt);
            }
        });
        fileMenu.add(fileQuit);

        mainMenu.add(fileMenu);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileAddUserActionPerformed

    private void fileQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileQuitActionPerformed

    private void fileViewProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileViewProfileMouseClicked
        // TODO add your handling code here:
        controller.showUserProfile();
    }//GEN-LAST:event_fileViewProfileMouseClicked

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        
    }//GEN-LAST:event_fileMenuActionPerformed

    private void fileViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileViewProfileActionPerformed
        // TODO add your handling code here:
        controller.showUserProfile();
    }//GEN-LAST:event_fileViewProfileActionPerformed

    private void fieldFilterSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFilterSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFilterSectionActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        System.out.println(userTable.rowAtPoint(evt.getPoint()));
        if(evt.getClickCount() == 2){
            controller.editUserFromTable(userTable.rowAtPoint(evt.getPoint()));
        }
    }//GEN-LAST:event_userTableMouseClicked

    private void contentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMouseClicked

    private void contentStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_contentStateChanged
        // TODO add your handling code here:
        if(content.getSelectedIndex() == 1){
            controller.loadUsersToTable();
        } else if(content.getSelectedIndex() == 1){
            controller.loadEvents();
        }
    }//GEN-LAST:event_contentStateChanged

    private void btnAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddUserMouseClicked
        // TODO add your handling code here:
        controller.addNewUser();
    }//GEN-LAST:event_btnAddUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JTabbedPane content;
    private cz.cvut.fel.dbs.smartorchestra.gui.ShowEvents events;
    private javax.swing.JComboBox<String> fieldFilterSection;
    private javax.swing.JTextField fieldSearchUser;
    private javax.swing.JMenuItem fileAddEvent;
    private javax.swing.JMenuItem fileAddUser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileQuit;
    private javax.swing.JPopupMenu.Separator fileSeparator1;
    private javax.swing.JPopupMenu.Separator fileSeparator2;
    private javax.swing.JMenuItem fileViewProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelFilterSection;
    private javax.swing.JLabel labelSearchUser;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JScrollPane userContent;
    private javax.swing.JTable userTable;
    private javax.swing.JToolBar userToolbar;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void setUIController(MainControl controller) {
        this.controller = controller;
    }

    @Override
    public MainControl getUIController() {
        return controller;
    }
    
    public void fetchUserIntoTable(List<Users> users){
        DefaultTableModel tableContent = new DefaultTableModel(
                new Object[][] {{}, {}},                        
                Main.USERS_COLUMN_NAMES){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
                    
                };
        tableContent.setRowCount(0);
        for(Users user : users){
            tableContent.addRow(new String[]{
                    user.getFamilyName(),
                    user.getFirstName(),
                    new SimpleDateFormat("dd.MM.yyyy").format(user.getBirthDate()),
                    user.getAddrTown(),
                    user.getPhone(),
                    user.getEmail(),
                    "sekce"                    
            });
        }
        userTable.setModel(tableContent);
        fetchColumns();
    }
    
    private void fetchColumns(){
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(2).setPreferredWidth(120);
            userTable.getColumnModel().getColumn(3).setResizable(false);
            userTable.getColumnModel().getColumn(3).setPreferredWidth(175);
            userTable.getColumnModel().getColumn(4).setResizable(false);
            userTable.getColumnModel().getColumn(4).setPreferredWidth(200);
            userTable.getColumnModel().getColumn(5).setResizable(false);
            userTable.getColumnModel().getColumn(5).setPreferredWidth(250);
            userTable.getColumnModel().getColumn(6).setResizable(false);
            userTable.getColumnModel().getColumn(6).setPreferredWidth(100);
        }
    }

    public ShowEvents getEvents() {
        return events;
    }
}
