/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cvut.fel.dbs.smartorchestra.gui;

import cz.cvut.fel.dbs.smartorchestra.MainControl;
import cz.cvut.fel.dbs.smartorchestra.SmartOrchestra;
import cz.cvut.fel.dbs.smartorchestra.UIControlled;

/**
 *
 * @author Matěj Bartoň
 */
public class Main extends javax.swing.JFrame implements UIControlled<MainControl>{
    private MainControl controller;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setUIController(SmartOrchestra.getController(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        content = new javax.swing.JTabbedPane();
        events = new cz.cvut.fel.dbs.smartorchestra.gui.ShowEvents();
        users = new cz.cvut.fel.dbs.smartorchestra.gui.ShowUsers();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileAddEvent = new javax.swing.JMenuItem();
        fileAddUser = new javax.swing.JMenuItem();
        fileSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileViewProfile = new javax.swing.JMenuItem();
        fileSeparator2 = new javax.swing.JPopupMenu.Separator();
        fileQuit = new javax.swing.JMenuItem();

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(18, 40));
        jToolBar1.setMinimumSize(new java.awt.Dimension(18, 40));

        jButton1.setText("Přidat událost");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Přidat uživatele");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setText("Můj profil");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        setName("SmartOrchestra"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 400));

        content.addTab("Přehled událostí", events);

        users.setEnabled(false);
        content.addTab("Přehled uživatelů", users);

        getContentPane().add(content, java.awt.BorderLayout.PAGE_START);

        fileMenu.setText("Soubor");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        fileAddEvent.setText("Přidat událost");
        fileAddEvent.setEnabled(false);
        fileMenu.add(fileAddEvent);

        fileAddUser.setText("Přidat uživatele");
        fileAddUser.setEnabled(false);
        fileAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileAddUserActionPerformed(evt);
            }
        });
        fileMenu.add(fileAddUser);
        fileMenu.add(fileSeparator1);

        fileViewProfile.setText("Zobrazit profil");
        fileViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileViewProfileMouseClicked(evt);
            }
        });
        fileViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileViewProfileActionPerformed(evt);
            }
        });
        fileMenu.add(fileViewProfile);
        fileMenu.add(fileSeparator2);

        fileQuit.setText("Ukončit aplikaci");
        fileQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileQuitActionPerformed(evt);
            }
        });
        fileMenu.add(fileQuit);

        mainMenu.add(fileMenu);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileAddUserActionPerformed

    private void fileQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileQuitActionPerformed

    private void fileViewProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileViewProfileMouseClicked
        // TODO add your handling code here:
        System.out.println("Turning on controller");
        controller.showUserProfile();
    }//GEN-LAST:event_fileViewProfileMouseClicked

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        
    }//GEN-LAST:event_fileMenuActionPerformed

    private void fileViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileViewProfileActionPerformed
        // TODO add your handling code here:
        controller.showUserProfile();
    }//GEN-LAST:event_fileViewProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane content;
    private cz.cvut.fel.dbs.smartorchestra.gui.ShowEvents events;
    private javax.swing.JMenuItem fileAddEvent;
    private javax.swing.JMenuItem fileAddUser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileQuit;
    private javax.swing.JPopupMenu.Separator fileSeparator1;
    private javax.swing.JPopupMenu.Separator fileSeparator2;
    private javax.swing.JMenuItem fileViewProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar mainMenu;
    private cz.cvut.fel.dbs.smartorchestra.gui.ShowUsers users;
    // End of variables declaration//GEN-END:variables

    @Override
    public final void setUIController(MainControl controller) {
        this.controller = controller;
    }

    @Override
    public MainControl getUIController() {
        return controller;
    }
}
